

name: Get Default Branch Name
on:
  workflow_call:
    outputs:
      default_branch:
        description: The name of the default branch
        value: ${{ jobs.get_default_branch.outputs.default_branch }}

jobs:
  get_default_branch:
    runs-on: ubuntu-22.04
    outputs:
      default_branch: ${{ steps.set_output.outputs.default_branch }}
    steps:
      - name: Retrieve default branch name
        id: default_branch
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          retries: 2
          script: |
            const { data } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const mainBranchName = data.default_branch;
            return mainBranchName;
      - name: Set output
        id: set_output
        run: |
          echo default_branch=${{ steps.default_branch.outputs.result }} >> $GITHUB_OUTPUT
